[project]
name = "financial-market-simulator"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "torch",
    "wandb",
    "python-dotenv",
    "yfinance>=1.7.0",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pylint.format]
max-line-length = 79
