name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.12.10"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run pylint
        run: uv run pylint src/generative_models tests

      - name: Run tests
        run: uv run pytest
